### ISSUE TITLE
Which License ?

### ISSUE THREAD

**Issue by RobertoMalatesta** [JamesGriffin/3D-Rasterizer#1]
Hi James,
really nice piece of code.

I don't see any license specified.
Can you specify it?

(My suggestion is liberal one like MIT, BSD  or Apache, since GPL is really troublesome)

R

**Comment by JamesGriffin** [comment]
Hi Roberto,

Apologies for the long delay, I somehow managed to miss this.

I've gone ahead and added the MIT license.

Cheers,
James
