### ISSUE TITLE
Texturing

### ISSUE THREAD

**Issue by AmigaBlitter** [JamesGriffin/3D-Rasterizer#2]
This is not really an issue, but no other way to contact you.

Could you implement, please, texturing?

**Comment by JamesGriffin** [comment]
Hey there,

I'm afraid I don't currently have the time to implement this at the moment however you may be interested in taking a look at my path tracer project which does support textures:
https://github.com/JamesGriffin/Path-Tracer

**Comment by AmigaBlitter** [comment]
Thank you very much for the reply.

Your project are very interesting.

I need only a simple obj load and display to implement in a little game.

As per your path tracer project is really impressive. I will have for sure
a look at it.

Thank you again for the reply.

Kind regards
Davide C.

Il giorno gio 14 gen 2021 alle ore 18:59 James Griffin <
notifications@github.com> ha scritto:
